import type { Meta, StoryObj } from '@storybook/react';
import BulletChart from './BulletChart';
declare const meta: Meta<typeof BulletChart>;
export default meta;
type Story = StoryObj<typeof BulletChart>;
export declare const Populated: Story;
export declare const DarkMode: Story;
export declare const Categories: Story;
export declare const ManyRows: Story;
export declare const LongNames: Story;
export declare const Negative: Story;
export declare const SingleRow: Story;
export declare const Empty: Story;
export declare const Loading: Story;
export declare const Error: Story;
export declare const FilterBadActive: Story;
export declare const SortByDeltaPlan: Story;
export declare const MoreIsBetter: Story;
export declare const SmallWidth: Story;
export declare const SmallHeight: Story;
//# sourceMappingURL=BulletChart.stories.d.ts.map